"""Generate SKINS_INDEX.md from the filesystem. Measured, never hand-authored."""
import hashlib
import io
import json
import os

from PIL import Image

ROOT = r"D:\Game builds\WulfPack-Mods\RuneCompass\Assets\Skins"

LIVE = [
    ("base.png", "baseTexture", "static backing plate", "full dial"),
    ("ring.png", "ringTexture", "the dial face; fixed, carries N/E/S/W", "full dial"),
    ("character_arrow.png", "characterArrowTexture",
     "THE needle: which way the character faces", "~45% centred"),
    ("camera_wedge.png", "cameraWedgeTexture",
     "where the camera looks; quiet background sector", "~86%, 60 deg span"),
    ("wind_gust.png", "windGustTexture",
     "small rune orbiting OUTSIDE the rim, marking the quarter wind comes FROM",
     "~13%, drawn centred"),
]
DEAD = [
    ("wind_pointer.png", "the centre-mounted wind spear; wind moved outside the rim"),
    ("lubber_marker.png", "a fixed rim chevron from the abandoned heading-up model"),
]

skins = sorted(d for d in os.listdir(ROOT) if os.path.isdir(os.path.join(ROOT, d)))
digest_owner = {}
rows, dead_rows = [], []
present = missing = 0

for skin in skins:
    for fname, key, role, size in LIVE:
        p = os.path.join(ROOT, skin, fname)
        if os.path.isfile(p):
            h = hashlib.md5(open(p, "rb").read()).hexdigest()[:8]
            w, ht = Image.open(p).size
            dup = digest_owner.get(h)
            digest_owner.setdefault(h, f"{skin}/{fname}")
            note = f"duplicate of `{dup}`" if dup else ""
            rows.append((skin, fname, "present", f"{w}x{ht}", h, note))
            present += 1
        else:
            rows.append((skin, fname, "MISSING", "-", "-", "falls back to primitive"))
            missing += 1
    for fname, why in DEAD:
        p = os.path.join(ROOT, skin, fname)
        if os.path.isfile(p):
            h = hashlib.md5(open(p, "rb").read()).hexdigest()[:8]
            dup = digest_owner.get(h)
            digest_owner.setdefault(h, f"{skin}/{fname}")
            dead_rows.append((skin, fname, h,
                              f"duplicate of `{dup}`" if dup else "", why))

total = present + missing
out = io.StringIO()
w = out.write
w("# Rune Compass — skins index\n\n")
w("**Generated by measurement, not by hand.** Regenerate with\n")
w("`verify-local.ps1`, which fails if this file disagrees with the filesystem.\n")
w("`docs/SHADOW_GENOME.md` Failure #7 is what that check exists to prevent: an index that\n")
w("had been reporting numbers nobody had measured, for its whole life.\n\n")
w("Authoring rules for every asset below: `RuneCompass/Assets/Skins/ART_SPEC.md`.\n\n")
w("## Coverage\n\n")
w(f"- Skins: **{len(skins)}**\n")
w(f"- Live assets required: **{total}** ({len(LIVE)} per skin)\n")
w(f"- Present: **{present}**\n")
w(f"- Missing: **{missing}** — each falls back to mod-drawn primitive geometry with\n")
w("  identical motion, so every skin stays playable while its art is finished\n\n")
w("## Folder structure\n\n")
w("```text\nRuneCompass/Assets/Skins/\n")
w("├── ART_SPEC.md          authoring rules: canvas, orientation, palettes\n")
w("├── SKINS_INDEX.md       this file\n")
for skin in skins:
    w(f"├── {skin}/\n")
    w("│   ├── skin.json\n")
    for fname, _, _, _ in LIVE:
        w(f"│   ├── {fname}\n")
w("```\n\n")
w("Filenames are canonical: the loader reads whatever `skin.json` names, but keeping them\n")
w("uniform is what lets this index be generated rather than maintained.\n\n")
w("## Assets\n\n")
w("| skin | file | status | size | hash | note |\n|---|---|---|---|---|---|\n")
for r in rows:
    w(f"| {r[0]} | `{r[1]}` | {'**MISSING**' if r[2]=='MISSING' else r[2]} | {r[3]} | `{r[4]}` | {r[5]} |\n")
w("\n## Roles\n\n")
w("| file | `skin.json` key | role | artwork occupies |\n|---|---|---|---|\n")
for fname, key, role, size in LIVE:
    w(f"| `{fname}` | `{key}` | {role} | {size} |\n")
if dead_rows:
    w("\n## Superseded — still on disk, never rendered\n\n")
    w("Safe to delete. The loader still reads these keys; nothing mounts the result.\n\n")
    w("| skin | file | hash | note | why dead |\n|---|---|---|---|---|\n")
    for r in dead_rows:
        w(f"| {r[0]} | `{r[1]}` | `{r[2]}` | {r[3]} | {r[4]} |\n")

io.open(os.path.join(ROOT, "SKINS_INDEX.md"), "w", encoding="utf-8", newline="\n").write(
    out.getvalue())

manifest = {
    "skins": skins,
    "liveAssets": [f for f, _, _, _ in LIVE],
    "deadAssets": [f for f, _ in DEAD],
    "present": present,
    "missing": missing,
}
io.open(os.path.join(ROOT, "skins-index.json"), "w", encoding="utf-8", newline="\n").write(
    json.dumps(manifest, indent=2) + "\n")
print(f"index written: {present} present, {missing} missing, {len(dead_rows)} dead")
